### ISSUE TITLE
TwelveHour clock still being shown after disabling

### ISSUE THREAD

**Issue by niranjans** [chingyawhao/materialize-clockpicker#23]
I have the initialization as:

```
$('#startDatetime').pickatime({
          autoclose: true,
          twelvehour: false
        });
```

However, the clock still comes up as this:
![screen shot 2016-10-10 at 4 24 04 pm](https://cloud.githubusercontent.com/assets/2230409/19254198/274b768a-8f06-11e6-95e7-b209014c77d8.png)

Am I missing something here?

**Comment by fabyeah** [comment]
That is the 24hour clock!?

**Comment by niranjans** [comment]
Yes. The only way to get the 24 hour clock is by adding `twelvehour: false` in the options right?

If so, that is what I did and I get the 24 hour clock with the 12 hour also showing in the inner circle like in the image.

**Comment by fabyeah** [comment]
The 24 hour clock is composed of both rings. There are 24 numbers, from 1 to 00. Putting them all in one ring would squeeze the numbers too tight, especially on mobile.

If you choose the 12 hour clock, you only get the inner ring, with numbers from 1 to 12.

This is the correct behavior. Check it out on your phone.

**Comment by niranjans** [comment]
Ahh right! My bad.. I completely missed the fact that the outer ring did not have 1-12. Makes sense. Thanks for the package!
