### ISSUE TITLE
afterDone callback not working as shown in readme

### ISSUE THREAD

**Issue by akatriel** [chingyawhao/materialize-clockpicker#28]
I tested the code from the readme and the last section contains the code
`<script>
  $('#timepicker').pickatime({
    autoclose: false,
    twelvehour: false,
    afterDone: function(Element, Time) {
        console.log(Element, Time);
    }
  });
</script>`

After testing the callback, undefined is returned for both Element and Time.
Is there a callback for when someone completes the picking process?

**Comment by dellert** [comment]
Same problem

**Comment by michael-wolfram-tgh** [comment]
There are missing parameters in function call. Replace line 1508 with following line:

raiseCallback(this.options.afterDone(this.input, submit));

Now, informations will be returned ;)
