### ISSUE TITLE
opening inside a input box, not popping.

### ISSUE THREAD

**Issue by nasr18** [chingyawhao/materialize-clockpicker#3]
I need a time picker for my materializecss web project. your project working fine. but after adding your css and js, its not popping. simply displaying inside input box. Any fix????

**Comment by chingyawhao** [comment]
Can u provide some examples..?

**Comment by nasr18** [comment]
now i removed that timepicker from my project. but i really need that. will show you the Screenshot after implementing in my proj.

**Comment by nasr18** [comment]
![screenshot from 2016-04-28 16 00 20](https://cloud.githubusercontent.com/assets/7514936/14883184/5f18d072-0d5a-11e6-904c-81f138005a97.png)

See this........... this is my issue. Not popping up like normal materializecss datepicker. Its displaying inside text box. @chingyawhao 

**Update:**
Found the issue why its appearing inside input box. I'm having time picker in a modal, so why its not popping out. But if i place this time picker other than modal means working fine. How do i make this work in a modal???

**Comment by chingyawhao** [comment]
Did u try materialize date picker...is it the same case..?
Sorry...I m focusing my final examination in school this few weeks...
I'll look into it after the exam

Regards
Ching Yaw Hao

**Comment by nasr18** [comment]
materialize date picker working fine in modal.

**Comment by chingyawhao** [comment]
This should solve your problem for now
Its appending to the body of the document instead
Check if this works
I might include this in my next update...I want to check how materialize
did their datepicker when I m free

On Tue, May 3, 2016 at 12:18 PM, Mohamed Nasrullah <notifications@github.com

**Comment by MasterChief93** [comment]
I'm using this timepicker along with datepicker from Materialize and sometimes datepicker opens instead of timepicker. There is a workaround in order to solve this? 

Thanks for your time! Your project is very useful!

**Comment by chingyawhao** [comment]
There is an additional option available 'container' that allows user to specify which container timepicker should open in
