### ISSUE TITLE
Rename picker__date-display to get compatibility with datepicker from materialize.

### ISSUE THREAD

**Issue by Poeschl** [chingyawhao/materialize-clockpicker#36]
I'm using your clockpicker library in combination with the timepicker from materialize.

Both of them are using the picker__date-display class for the div containing the date or the time. By using the same class the styling gets overridden.

Is it possible to change the class maybe to picker__time-display? If so, I could offer a pull request.

**Comment by tomscholz** [comment]
We added a timepicker in materialize. It will be available with the next release

**Comment by MacGyer** [comment]
@tomscholz Sounds good.
Any information on which library is being used?

Thanks

**Comment by Poeschl** [comment]
Well, that will do for me ;)

(I know its a bad thing to ask for a eta. Maybe you have a rough month for me)

**Comment by tomscholz** [comment]
See: https://github.com/Dogfalo/materialize/pull/4445
