### ISSUE TITLE
Materialize Timepicker does not display well 

### ISSUE THREAD

**Issue by NajwaLaabid** [chingyawhao/materialize-clockpicker#39]
Hey everyone!

I am using materialize timepicker in my project, and I can't get it to display correctly.

Here's what I get:

![screenshot](https://user-images.githubusercontent.com/17838639/29328513-c2fadf6c-81ea-11e7-87ed-b32063a81f7c.PNG)

Here's what I should get:

![screen1](https://user-images.githubusercontent.com/17838639/29328559-de80a7f8-81ea-11e7-9091-f6ddeb43e50d.PNG)

Here's my code: [demo](https://jsfiddle.net/oaeu0tbn/)

`<div class="input-field">
    <i class="material-icons prefix">access_time</i>
    <input id="pts_start" name="pts_start" type="text" class="timepicker" required/>
    <label for="pts_start">Start Time</label>
  </div>
</div>`

**Comment by tomscholz** [comment]
You are initializing a datepicker as a timepicker.
Please close...

**Comment by NajwaLaabid** [comment]
@tomscholz my bad I pasted the wrong code. I am working on a fiddle to make it clearer, but I have a problem importing materialize files.

Here's what I have so far: [fiddle](https://jsfiddle.net/oaeu0tbn/)

**Comment by tomscholz** [comment]
You forgot to include jquery in your fiddle
